### Load file dataset từ formatted_jobs.csv

#### Việc cần làm
1. Load data
2. Clean text
3. Tạo combined_text cho từng job
4. Group theo Industry (chỉ để build vocab)

5. Với từng Industry:
   a. tokenize
   b. remove stopwords (custom)
   c. build frequency

6. Build word families:
   - stem → tạo group
   - remove outlier nhẹ

7. Chọn canonical word:
   - theo frequency
   - giữ word thật (không dùng stem)

8. Build mapping:
   activity → active

9. Rewrite từng job (KHÔNG phải industry text)

10. Vector hóa (TF-IDF)

11. Matching job ↔ candidate

In [2]:
import numpy as np
import pandas as pd
import re

In [3]:
def load_data(file_path): 
    df = pd.read_csv(file_path)
    required_cols = ['job_title', 'Short_description', 'Skills_required', 'Industry', 'Pay_grade']
    missing = [col for col in required_cols if col not in df.columns]
    if missing: 
        raise ValueError(f"Dữ liệu thiếu cột: {', '.join(missing)}")
    df= df.copy(
        
    )
    df = df.dropna(subset=['Industry']) 
    return df

In [6]:
df = load_data(r'E:\Semester6\Laptrinhpython\project\data\formatted_jobs.csv')
df.head()
df.info()
# kieerm tra cos bao nhieu loaij industry khac nhau
print("Tổng Industry: ")
print(df['Industry'].nunique())

<class 'pandas.DataFrame'>
RangeIndex: 970 entries, 0 to 969
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID_num             970 non-null    int64
 1   job_title          970 non-null    str
 2   Short_description  970 non-null    str
 3   Skills_required    970 non-null    str
 4   Industry           970 non-null    str
 5   Pay_grade          970 non-null    str
dtypes: int64(1), str(5)
memory usage: 45.6 KB
Tổng Industry:
105

In [ ]:
# 1. Thống kê số lượng dòng cho mỗi Industry
industry_counts = df['Industry'].value_counts()

print("Thống kê số lượng công việc theo từng ngành nghề:")
print(industry_counts)

# 2. (Tùy chọn) Nếu bạn muốn xem dưới dạng phần trăm (%)
industry_percent = df['Industry'].value_counts(normalize=True) * 100
print("\nPhần trăm tỷ trọng của từng ngành nghề:")
print(industry_percent)

Thống kê số lượng công việc theo từng ngành nghề:
Industry
Technology         197
Marketing           94
Healthcare          56
Education           36
Human Resources     35
                  ...
Fishing              1
Food Services        1
Energy Services      1
Arts & Sciences      1
Energy               1
Name: count, Length: 105, dtype: int64

Phần trăm tỷ trọng của từng ngành nghề:
Industry
Technology         20.309278
Marketing           9.690722
Healthcare          5.773196
Education           3.711340
Human Resources     3.608247
                     ...
Fishing             0.103093
Food Services       0.103093
Energy Services     0.103093
Arts & Sciences     0.103093
Energy              0.103093
Name: proportion, Length: 105, dtype: float64

In [8]:
# 1. Gộp các cột văn bản lại để tính toán vocab (loại bỏ giá trị NaN nếu có)
text_columns = ['job_title', 'Short_description', 'Skills_required']
df['all_text'] = df[text_columns].fillna('').agg(' '.join, axis=1)

# 2. Hàm định nghĩa cách tính số lượng từ duy nhất (Vocab size)
def count_unique_vocab(text_series):
    # Kết hợp toàn bộ văn bản của tất cả các dòng trong nhóm thành 1 chuỗi lớn
    full_content = " ".join(text_series).lower()
    # Sử dụng Regex để chỉ lấy các ký tự chữ và số (loại bỏ dấu câu)
    words = re.findall(r'\w+', full_content)
    # Trả về số lượng từ không trùng lặp
    return len(set(words))

# 3. Gom nhóm theo Industry và thực hiện tính toán đồng thời
# 'size' để đếm số dòng, 'count_unique_vocab' là hàm tự định nghĩa ở trên
summary_df = df.groupby('Industry').agg(
    So_luong_dong=('Industry', 'size'),
    Vocab_Size=('all_text', count_unique_vocab)
).reset_index()

# 4. Sắp xếp kết quả theo số lượng dòng giảm dần (tùy chọn)
summary_df = summary_df.sort_values(by='So_luong_dong', ascending=False)

# 5. Xuất ra file CSV
# 'utf-8-sig' giúp file CSV hiển thị đúng tiếng Việt khi mở bằng Excel
summary_df.to_csv('industry_stats.csv', index=False, encoding='utf-8-sig')

print("Đã tạo file 'industry_stats.csv' thành công!")
print(summary_df.head())

Đã tạo file 'industry_stats.csv' thành công!
           Industry  So_luong_dong  Vocab_Size
97       Technology            197         585
66        Marketing             94         219
51       Healthcare             56         324
25        Education             36         212
53  Human Resources             35         183

In [ ]:
SPECIAL_TOKEN_MAP = {
    "c++": "cpp",
    "c#": "csharp",
    ".net": "dotnet",
    "node.js": "nodejs",
    "react.js": "reactjs",
    "next.js": "nextjs",
    "vue.js": "vuejs",
    "nuxt.js": "nuxtjs",
    "express.js": "expressjs",
    "asp.net": "aspdotnet",
    "a.i": "ai",
    "m.l": "ml",
    "ui/ux": "uiux",
    "front-end": "frontend",
    "back-end": "backend",
    "full-stack": "fullstack",
    "data-science": "data_science",
    "machine-learning": "machine_learning",
    "deep-learning": "deep_learning",
    "problem-solving": "problem_solving",
    "decision-making": "decision_making",
}

def normalize_special_tokens(text):
    if pd.isna(text):
        return ""

    text = str(text).lower()

    # normalize khoảng trắng trước
    text = re.sub(r"\s+", " ", text).strip()

    # thay các cụm đặc biệt theo thứ tự từ dài tới ngắn
    for src in sorted(SPECIAL_TOKEN_MAP.keys(), key=len, reverse=True):
        dst = SPECIAL_TOKEN_MAP[src]
        text = text.replace(src, dst)

    return text

In [10]:
def cleanText(text):
    if pd.isna(text):
        return ""

    text = normalize_special_tokens(text)

    # bỏ các ký tự không cần, nhưng tạm vẫn giữ _, +, #, .
    text = re.sub(r"[^\w\s\+\#\.]", " ", text, flags=re.UNICODE)

    # loại các dấu chấm dư còn sót lại nếu không còn ý nghĩa
    text = re.sub(r"\.(?=\s|$)", " ", text)

    # bỏ + và # đứng một mình, nhưng token đã normalize như cpp/csharp thì không bị ảnh hưởng
    text = re.sub(r"(?<!\w)[\+\#]+(?!\w)", " ", text)

    # chuẩn hóa khoảng trắng
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [11]:
def formatTextColumns(df):
    df = df.copy()

    text_cols = ["job_title", "Short_description", "Skills_required", "Industry"]

    for col in text_cols:
        if col in df.columns:
            df[col] = df[col].fillna("").apply(cleanText)

    return df

# hàm này áp dụng cleanText cho tất cả các cột văn bản trong DataFrame

In [12]:
formatted_df = formatTextColumns(df)
formatted_df.head()

,ID_num,job_title,Short_description,Skills_required,Industry,Pay_grade
0,1,software engineer,develop and maintain web applications using mo...,problem solving logical reasoning attention to...,technology,High paying
1,2,data scientist,analyze large datasets to extract business ins...,analytical thinking pattern recognition mathem...,technology,High paying
2,3,marketing manager,lead marketing campaigns and brand strategy de...,creative thinking strategic planning communica...,marketing,Average paying
3,4,ux designer,design user friendly interfaces and improve us...,creative problem solving empathy research skil...,technology,Average paying
4,5,financial analyst,analyze financial data and prepare reports for...,analytical thinking attention to detail mathem...,finance,Average paying

In [13]:
def buildCombinedText(df):
    df = df.copy()

    df["combined_text"] = (
        df["job_title"].fillna("") + " " +
        df["Short_description"].fillna("") + " " +
        df["Skills_required"].fillna("")
    )

    df["combined_text"] = df["combined_text"].apply(lambda x: re.sub(r"\s+", " ", x).strip()) # hàm này chuẩn hóa khoảng trắng trong combined_text

    return df

In [15]:
built_df = buildCombinedText(formatted_df)
built_df = built_df[["Industry", "combined_text"]]
built_df.head()

     Industry                                      combined_text
0  technology  software engineer develop and maintain web app...
1  technology  data scientist analyze large datasets to extra...
2   marketing  marketing manager lead marketing campaigns and...
3  technology  ux designer design user friendly interfaces an...
4     finance  financial analyst analyze financial data and p...

In [16]:
import re
from collections import Counter, defaultdict
import pandas as pd
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

EN_STOPWORDS = set(stopwords.words("english"))

def tokenize_text(text):
    if pd.isna(text):
        return []
    
    text = str(text).strip().lower()
    
    # lấy token gồm chữ, số, underscore
    tokens = re.findall(r"\b[a-zA-Z0-9_]+\b", text)
    return tokens


def remove_stopwords(tokens, stop_words=EN_STOPWORDS, min_len=2):
    cleaned_tokens = [
        t for t in tokens
        if t not in stop_words and len(t) >= min_len
    ]
    return cleaned_tokens


def tokenize_and_remove_stopwords(text, stop_words=EN_STOPWORDS, min_len=2):
    tokens = tokenize_text(text)
    tokens = remove_stopwords(tokens, stop_words=stop_words, min_len=min_len)
    return tokens
# xây dựng token cho cột combined_text , loại bỏ stopwords

In [17]:
def build_vocabulary_by_industry(df, text_col="combined_text", industry_col="Industry"):
    vocab_by_industry = {}
    tokens_by_industry = {}

    grouped = df.groupby(industry_col)

    for industry, group_df in grouped:
        all_tokens = []

        for text in group_df[text_col].fillna(""):
            tokens = tokenize_and_remove_stopwords(text)
            all_tokens.extend(tokens)

        freq = Counter(all_tokens)

        vocab_by_industry[industry] = freq
        tokens_by_industry[industry] = all_tokens

    return vocab_by_industry, tokens_by_industry

In [20]:
vocab_by_industry, tokens_by_industry = build_vocabulary_by_industry(built_df)

list(vocab_by_industry.keys())
tokens_by_industry.keys()

dict_keys(['advertising', 'aerospace', 'agriculture', 'animal sciences', 'animal services', 'architecture', 'art antiques', 'arts crafts', 'arts culture', 'arts sciences', 'automotive', 'aviation', 'biotechnology', 'business services', 'cleaning services', 'construction', 'consulting', 'corporate governance', 'cosmetics', 'creative services', 'cultural heritage', 'customer service', 'design services', 'earth sciences', 'economics', 'education', 'emergency services', 'energy', 'energy research', 'energy services', 'engineering', 'entertainment', 'environmental sciences', 'environmental services', 'event planning', 'executive leadership', 'facilities management', 'fashion', 'finance', 'financial services', 'fishing', 'fitness recreation', 'food production', 'food science', 'food service', 'food services', 'forensic science', 'forestry', 'funeral services', 'gaming', 'government', 'healthcare', 'hospitality', 'human resources', 'insurance', 'international trade', 'jewelry', 'landscaping', 'law enforcement', 'legal services', 'logistics', 'maintenance services', 'manufacturing', 'mapping surveying', 'marine science', 'maritime', 'marketing', 'media publishing', 'mining resources', 'moving services', 'nonprofit', 'oil gas', 'personal care', 'personal services', 'pest control', 'pet services', 'photography', 'postal services', 'professional services', 'public safety', 'real estate', 'recreation', 'regulatory affairs', 'renewable energy', 'research development', 'retail', 'risk management', 'robotics', 'safety compliance', 'sales', 'science research', 'security', 'social sciences', 'social services', 'space science', 'specialized services', 'sports', 'technology', 'tourism', 'transportation', 'travel tourism', 'urban development', 'warehousing', 'weather services', 'wellness'])

In [21]:
stemmer = PorterStemmer()

def group_family_words(freq_dict):
    stem_groups = defaultdict(list)

    for word, count in freq_dict.items():
        stem = stemmer.stem(word)
        stem_groups[stem].append((word, count))

    return stem_groups
# gom các family words lại với nhau, ví dụ như "develop", "developer", "development" sẽ có cùng gốc là "develop" và được gom vào cùng một nhóm.
# stem_groups sẽ có dạng vd: {"develop": [("develop", 100), ("developer", 80), ("development", 60)], ...}

In [25]:
grouped_vocab_by_industry = {}
for industry, freq_dict in vocab_by_industry.items():
    grouped_vocab_by_industry[industry] = group_family_words(freq_dict)
print(grouped_vocab_by_industry["technology"])

defaultdict(<class 'list'>, {'softwar': [('software', 20)], 'engin': [('engineer', 13), ('engineering', 14)], 'develop': [('develop', 12), ('developer', 13), ('development', 19)], 'maintain': [('maintain', 9)], 'web': [('web', 4)], 'applic': [('applications', 12), ('application', 2)], 'use': [('using', 3), ('use', 3)], 'modern': [('modern', 1)], 'framework': [('frameworks', 2)], 'problem': [('problem', 42)], 'solv': [('solving', 42)], 'logic': [('logical', 5)], 'reason': [('reasoning', 8)], 'attent': [('attention', 14)], 'detail': [('detail', 14)], 'team': [('team', 11), ('teams', 14)], 'collabor': [('collaboration', 3)], 'critic': [('critical', 6)], 'think': [('thinking', 14)], 'data': [('data', 35)], 'scientist': [('scientist', 2)], 'analyz': [('analyze', 14)], 'larg': [('large', 2)], 'dataset': [('datasets', 1)], 'extract': [('extract', 1)], 'busi': [('business', 4)], 'insight': [('insights', 9)], 'build': [('build', 6), ('building', 5)], 'predict': [('predictive', 1)], 'model': [('models', 5), ('modeling', 3), ('model', 1)], 'analyt': [('analytical', 1), ('analytics', 60)], 'pattern': [('pattern', 1), ('patterns', 1)], 'recognit': [('recognition', 3)], 'mathemat': [('mathematical', 1), ('mathematics', 1)], 'research': [('research', 15), ('researcher', 2)], 'skill': [('skills', 16)], 'ux': [('ux', 23)], 'design': [('designer', 10), ('design', 40)], 'user': [('user', 43), ('users', 7)], 'friendli': [('friendly', 1)], 'interfac': [('interfaces', 4), ('interface', 2)], 'improv': [('improve', 8), ('improvement', 1)], 'experi': [('experience', 28), ('experiences', 4)], 'creativ': [('creative', 4), ('creativity', 7)], 'empathi': [('empathy', 3)], 'visual': [('visual', 3), ('visualizations', 1)], 'center': [('centered', 2)], 'network': [('network', 6), ('networks', 1), ('networking', 2)], 'administr': [('administrator', 4), ('administration', 1)], 'troubleshoot': [('troubleshoot', 2), ('troubleshooting', 9)], 'comput': [('computer', 4)], 'system': [('systems', 28), ('system', 8)], 'technic': [('technical', 51)], 'patienc': [('patience', 2)], 'devop': [('devops', 4)], 'implement': [('implement', 3), ('implementations', 1), ('implementation', 1)], 'ci': [('ci', 2)], 'cd': [('cd', 2)], 'pipelin': [('pipelines', 3)], 'manag': [('manage', 13), ('manager', 14), ('management', 51)], 'cloud': [('cloud', 6)], 'infrastructur': [('infrastructure', 7)], 'autom': [('automation', 7), ('automated', 2)], 'mindset': [('mindset', 1)], 'continu': [('continuous', 3)], 'learn': [('learning', 15)], 'qualiti': [('quality', 10)], 'assur': [('assurance', 5)], 'tester': [('tester', 7)], 'test': [('test', 8), ('testing', 14)], 'identifi': [('identify', 1), ('identifying', 1)], 'bug': [('bugs', 1), ('bug', 1)], 'ensur': [('ensure', 6)], 'systemat': [('systematic', 1)], 'websit': [('websites', 3)], 'variou': [('various', 2)], 'program': [('programming', 15), ('programs', 4), ('program', 2)], 'languag': [('languages', 2), ('language', 1)], 'adapt': [('adaptability', 1), ('adapt', 1)], 'databas': [('database', 5)], 'integr': [('integrity', 2), ('integration', 2)], 'secur': [('security', 22), ('secure', 2)], 'awar': [('awareness', 5)], 'cybersecur': [('cybersecurity', 12)], 'analyst': [('analyst', 38)], 'monitor': [('monitor', 4), ('monitoring', 3)], 'protect': [('protect', 3), ('protection', 1)], 'threat': [('threats', 1)], 'ethic': [('ethical', 4), ('ethics', 3)], 'mobil': [('mobile', 2)], 'app': [('app', 3), ('apps', 2)], 'io': [('ios', 1)], 'android': [('android', 1)], 'platform': [('platforms', 5)], 'innov': [('innovation', 20)], 'product': [('product', 130), ('products', 37), ('productive', 1), ('production', 2)], 'defin': [('define', 3)], 'strategi': [('strategy', 28), ('strategies', 2)], 'coordin': [('coordinate', 2), ('coordinator', 7), ('coordination', 1)], 'strateg': [('strategic', 5)], 'leadership': [('leadership', 36)], 'commun': [('communication', 140), ('community', 20), ('communities', 1)], 'market': [('market', 5), ('marketing', 2), ('markets', 1)], 'decis': [('decision', 2), ('decisions', 3)], 'make': [('making', 2)], 'blockchain': [('blockchain', 3)], 'creat': [('create', 16)], 'decentr': [('decentralized', 2)], 'cryptocurr': [('cryptocurrency', 3)], 'cryptographi': [('cryptography', 4)], 'distribut': [('distributed', 7)], 'protocol': [('protocols', 7)], 'hacker': [('hacker', 2)], 'vulner': [('vulnerabilities', 2)], 'cryptograph': [('cryptographer', 1)], 'encrypt': [('encryption', 1)], 'holograph': [('holographic', 1)], 'three': [('three', 1)], 'dimension': [('dimensional', 1)], 'display': [('displays', 1)], '3d': [('3d', 3)], 'optic': [('optical', 1)], 'physic': [('physics', 3), ('physical', 2)], 'vision': [('vision', 2)], 'virtual': [('virtual', 8)], 'realiti': [('reality', 3)], 'immers': [('immersive', 1)], 'digit': [('digital', 160)], 'spatial': [('spatial', 2)], 'artifici': [('artificial', 2)], 'intellig': [('intelligence', 2)], 'trainer': [('trainer', 4)], 'train': [('train', 1), ('training', 17)], 'machin': [('machine', 9)], 'scienc': [('science', 6)], 'algorithm': [('algorithm', 1), ('algorithms', 1)], 'intuit': [('intuitive', 2)], 'principl': [('principles', 1)], 'psycholog': [('psychology', 2)], 'prototyp': [('prototyping', 5)], 'consult': [('consultant', 4), ('consulting', 1)], 'advis': [('advise', 3)], 'organ': [('organizations', 4), ('organization', 17), ('organize', 3)], 'risk': [('risk', 6)], 'assess': [('assessment', 9), ('assessments', 1)], 'plan': [('planning', 1), ('plan', 2)], 'wearabl': [('wearable', 1)], 'technolog': [('technology', 116), ('technologies', 1)], 'smart': [('smart', 3)], 'devic': [('devices', 2)], 'health': [('health', 1)], 'equip': [('equipment', 1)], 'electron': [('electronics', 1)], 'augment': [('augmented', 1)], 'blend': [('blend', 1)], 'world': [('worlds', 1), ('world', 1)], 'telepres': [('telepresence', 1)], 'robot': [('robot', 1), ('robots', 2), ('robotics', 2)], 'oper': [('operator', 1), ('operations', 5)], 'control': [('control', 3)], 'remot': [('remote', 67)], 'mine': [('mining', 2)], 'currenc': [('currency', 1)], 'hardwar': [('hardware', 3)], 'energi': [('energy', 1)], 'twin': [('twin', 2)], 'replica': [('replicas', 1)], 'analysi': [('analysis', 18)], 'quantum': [('quantum', 5)], 'specialist': [('specialist', 8)], 'ultra': [('ultra', 2)], 'mechan': [('mechanics', 1)], 'swarm': [('swarm', 1)], 'group': [('groups', 9)], 'autonom': [('autonomous', 1)], 'work': [('working', 1)], 'togeth': [('together', 1)], 'sensor': [('sensor', 1)], 'precis': [('precise', 1)], 'measur': [('measurement', 1)], 'instrument': [('instruments', 1)], 'ai': [('ai', 13)], 'auditor': [('auditor', 2)], 'evalu': [('evaluate', 2)], 'bia': [('bias', 1)], 'fair': [('fairness', 1)], 'access': [('accessibility', 13), ('accessible', 1)], 'usabl': [('usable', 1), ('usability', 6)], 'peopl': [('people', 2)], 'disabl': [('disabilities', 2)], 'standard': [('standards', 5)], 'voic': [('voice', 4)], 'speech': [('speech', 1)], 'accuraci': [('accuracy', 2)], 'linguist': [('linguistics', 1)], 'audio': [('audio', 1)], 'process': [('processing', 1), ('processes', 2), ('process', 1)], 'privaci': [('privacy', 5)], 'individu': [('individuals', 2)], 'onlin': [('online', 53)], 'legal': [('legal', 1)], 'knowledg': [('knowledge', 5)], 'asset': [('asset', 3)], 'recoveri': [('recovery', 2)], 'help': [('help', 12)], 'retriev': [('retrieve', 1)], 'lost': [('lost', 1)], 'file': [('files', 1)], 'content': [('content', 23)], 'moder': [('moderator', 4), ('moderation', 1)], 'review': [('review', 5), ('reviews', 1)], 'filter': [('filter', 1)], 'appropri': [('appropriateness', 1)], 'cultur': [('cultural', 1)], 'safe': [('safe', 1)], 'discuss': [('discussion', 1)], 'space': [('spaces', 3)], 'conflict': [('conflict', 2)], 'resolut': [('resolution', 2)], 'event': [('events', 1)], 'director': [('director', 2)], 'confer': [('conferences', 1)], 'gather': [('gatherings', 1)], 'project': [('project', 12), ('projects', 2)], 'builder': [('builder', 1)], 'grow': [('grow', 1)], 'share': [('shared', 1)], 'interest': [('interests', 1)], 'goal': [('goals', 1)], 'social': [('social', 2)], 'media': [('media', 2)], 'relationship': [('relationship', 1)], 'overse': [('oversee', 11)], 'launch': [('launch', 4), ('launches', 2)], 'inclus': [('inclusive', 3)], 'solut': [('solutions', 6), ('solution', 1)], 'custom': [('customer', 23), ('customization', 2), ('customers', 1)], 'studi': [('study', 3), ('studies', 1)], 'interact': [('interactions', 2), ('interaction', 2), ('interact', 1)], 'satisfact': [('satisfaction', 1)], 'ml': [('ml', 1)], 'python': [('python', 3)], 'tensorflow': [('tensorflow', 1)], 'statist': [('statistics', 2)], 'architect': [('architect', 5)], 'comprehens': [('comprehensive', 1)], 'enterpris': [('enterprise', 5)], 'complianc': [('compliance', 6)], 'owner': [('owner', 1)], 'roadmap': [('roadmap', 3)], 'agil': [('agile', 4), ('agility', 1)], 'methodolog': [('methodologies', 3)], 'stakehold': [('stakeholder', 3)], 'scalabl': [('scalable', 1), ('scalability', 1)], 'migrat': [('migration', 1)], 'aw': [('aws', 1)], 'azur': [('azure', 1)], 'microservic': [('microservices', 1)], 'cost': [('cost', 1)], 'optim': [('optimization', 2), ('optimize', 6)], 'contract': [('contracts', 1)], 'solid': [('solidity', 1)], 'web3': [('web3', 1)], 'javascript': [('javascript', 1)], 'senior': [('senior', 3)], 'scale': [('scale', 1)], 'architectur': [('architecture', 7)], 'multipl': [('multiple', 1)], 'lead': [('lead', 58)], 'big': [('big', 1)], 'tool': [('tools', 18), ('tool', 3)], 'conduct': [('conduct', 2)], 'inform': [('inform', 1)], 'method': [('methods', 1)], 'provid': [('provide', 7)], 'expertis': [('expertise', 1)], 'support': [('support', 28)], 'sale': [('sales', 2)], 'success': [('success', 1)], 'writer': [('writer', 4)], 'document': [('documentation', 23)], 'write': [('writing', 12), ('write', 2)], 'understand': [('understanding', 1)], 'scrum': [('scrum', 1)], 'master': [('master', 1)], 'facilit': [('facilitate', 1), ('facilitation', 1)], 'valid': [('validation', 1), ('validator', 1)], 'track': [('tracking', 1), ('track', 3)], 'script': [('scripting', 3)], 'sql': [('sql', 2)], 'backup': [('backup', 1)], 'perform': [('performance', 4)], 'tune': [('tuning', 1)], 'engag': [('engaging', 1), ('engagement', 11)], 'desk': [('desk', 3)], 'technician': [('technician', 1)], 'first': [('first', 1)], 'level': [('level', 2)], 'end': [('end', 1)], 'servic': [('service', 11)], 'princip': [('principal', 5)], 'initi': [('initiatives', 3)], 'advanc': [('advanced', 5)], 'kubernet': [('kubernetes', 1)], 'code': [('code', 2), ('coding', 3)], 'wide': [('wide', 1)], 'complex': [('complex', 2)], 'mentor': [('mentoring', 2)], 'head': [('head', 2)], 'portfolio': [('portfolio', 3)], 'direct': [('direction', 1)], 'vp': [('vp', 2)], 'site': [('site', 1)], 'reliabl': [('reliability', 3)], 'incid': [('incident', 1)], 'respons': [('response', 2), ('responsible', 1)], 'junior': [('junior', 1)], 'guidanc': [('guidance', 1)], 'debug': [('debugging', 1)], 'version': [('version', 1)], 'issu': [('issues', 1)], 'instal': [('installation', 1), ('installer', 1)], 'client': [('client', 1), ('clients', 2)], 'cisco': [('cisco', 1)], 'excel': [('excellence', 2)], 'deliveri': [('delivery', 1)], 'workflow': [('workflows', 1)], 'cross': [('cross', 1)], 'function': [('functional', 1), ('functions', 1)], 'prompt': [('prompt', 2), ('prompts', 1)], 'nlp': [('nlp', 1)], 'experiment': [('experimentation', 1)], 'convers': [('conversational', 2), ('conversation', 1)], 'activ': [('activated', 1)], 'polici': [('policy', 4), ('policies', 1)], 'home': [('home', 3)], 'set': [('set', 2)], 'configur': [('configure', 1)], 'real': [('real', 1)], 'simul': [('simulation', 1)], 'iot': [('iot', 1)], 'report': [('reporting', 46), ('report', 3)], 'person': [('personal', 1), ('personalize', 1)], 'coach': [('coach', 1), ('coaching', 1)], 'live': [('lives', 1)], 'verifi': [('verify', 1)], 'label': [('labeling', 1)], 'supervisor': [('supervisor', 2)], 'tag': [('tagging', 1)], 'annot': [('annotation', 1)], 'safeti': [('safety', 9)], 'vr': [('vr', 2)], 'base': [('based', 1), ('base', 1)], 'instruct': [('instructional', 2)], 'interview': [('interviewer', 1), ('interviews', 1), ('interviewing', 1), ('interview', 1)], 'object': [('objectivity', 2)], 'resourc': [('resources', 2)], 'chatbot': [('chatbot', 3)], 'flow': [('flows', 1)], 'assist': [('assistants', 1)], 'new': [('new', 5)], 'account': [('account', 2)], 'afar': [('afar', 1)], 'boost': [('boost', 2)], 'particip': [('participation', 2)], 'feedback': [('feedback', 10)], 'collect': [('collect', 1)], 'manual': [('manuals', 2)], 'rollout': [('rollouts', 1)], 'offic': [('officer', 1)], 'advoc': [('advocate', 2)], 'promot': [('promote', 2)], 'tech': [('tech', 2)], 'advocaci': [('advocacy', 4)], 'eas': [('ease', 1)], 'journey': [('journey', 1)], 'map': [('map', 1)], 'guidelin': [('guidelines', 1)], 'driven': [('driven', 1)], 'assessor': [('assessor', 1)], 'candid': [('candidates', 1)], 'job': [('job', 1)], 'lifecycl': [('lifecycle', 1)], 'stage': [('stages', 1)], 'growth': [('growth', 17)], 'membership': [('membership', 1)], 'hack': [('hacking', 1)], 'local': [('localization', 3)], 'global': [('global', 1)], 'translat': [('translation', 3)], 'champion': [('champion', 1)], 'need': [('needs', 1)], 'crisi': [('crisis', 3)], 'handl': [('handle', 1)], 'emerg': [('emergencies', 1)], 'input': [('input', 1)], 'guid': [('guides', 1), ('guide', 1)], 'find': [('find', 1)], 'schedul': [('scheduler', 2), ('scheduling', 2)], 'timelin': [('timelines', 1)], 'beta': [('beta', 2)], 'tri': [('try', 1)], 'featur': [('features', 1), ('feature', 2)], 'mileston': [('milestones', 1)], 'check': [('check', 1)], 'releas': [('release', 4), ('releases', 1)], 'articl': [('articles', 1)], 'behavior': [('behavior', 1)], 'employe': [('employee', 1)], 'priorit': [('prioritization', 1)], 'rank': [('rank', 1)], 'idea': [('ideas', 1)], 'usag': [('usage', 2)], 'interpret': [('interpretation', 4)], 'abus': [('abuse', 1)], 'question': [('questions', 1)], 'creation': [('creation', 1)], 'suggest': [('suggestions', 1)], 'meet': [('meet', 1)], 'audit': [('auditing', 1), ('audit', 1)], 'teach': [('teach', 1)], 'best': [('best', 1)], 'practic': [('practices', 1)], 'dashboard': [('dashboard', 2)], 'persona': [('persona', 2)], 'profil': [('profiles', 1)], 'post': [('posts', 1)], 'describ': [('describe', 1)], 'saa': [('saas', 3)], 'marketplac': [('marketplace', 1)], 'fraud': [('fraud', 3)], 'detect': [('detect', 1), ('detection', 1)], 'prevent': [('prevent', 1)], 'commerc': [('commerce', 2)], 'investig': [('investigation', 1)], 'enforc': [('enforce', 1)], 'onboard': [('onboarding', 2)], 'setup': [('setup', 1)], 'qa': [('qa', 2)], 'deliv': [('deliver', 1)], 'curriculum': [('curriculum', 2)], 'drive': [('drive', 3)], 'increas': [('increase', 4)], 'loyalti': [('loyalty', 6)], 'enhanc': [('enhance', 2)], 'campaign': [('campaign', 8), ('campaigns', 4)], 'partnership': [('partnership', 4), ('partnerships', 8)], 'negoti': [('negotiation', 4)], 'retent': [('retention', 6)]})

In [27]:
def choose_canonical_word(stem_groups):
    family_mapping = {}
    canonical_info = {}

    for stem, items in stem_groups.items():
        # sort theo:
        # 1. frequency giảm dần
        # 2. độ dài tăng dần
        # 3. alphabet
        items_sorted = sorted(items, key=lambda x: (-x[1], len(x[0]), x[0]))
        canonical = items_sorted[0][0]

        canonical_info[stem] = {
            "canonical": canonical,
            "variants": items_sorted
        }

        for word, _ in items:
            family_mapping[word] = canonical

    return family_mapping, canonical_info

In [28]:
canonical_mapping_by_industry = {}
for industry, stem_groups in grouped_vocab_by_industry.items():
    mapping, info = choose_canonical_word(stem_groups)
    canonical_mapping_by_industry[industry] = mapping
print(canonical_mapping_by_industry["technology"])

{'software': 'software', 'engineer': 'engineering', 'engineering': 'engineering', 'develop': 'development', 'developer': 'development', 'development': 'development', 'maintain': 'maintain', 'web': 'web', 'applications': 'applications', 'application': 'applications', 'using': 'use', 'use': 'use', 'modern': 'modern', 'frameworks': 'frameworks', 'problem': 'problem', 'solving': 'solving', 'logical': 'logical', 'reasoning': 'reasoning', 'attention': 'attention', 'detail': 'detail', 'team': 'teams', 'teams': 'teams', 'collaboration': 'collaboration', 'critical': 'critical', 'thinking': 'thinking', 'data': 'data', 'scientist': 'scientist', 'analyze': 'analyze', 'large': 'large', 'datasets': 'datasets', 'extract': 'extract', 'business': 'business', 'insights': 'insights', 'build': 'build', 'building': 'build', 'predictive': 'predictive', 'models': 'models', 'modeling': 'models', 'model': 'models', 'analytical': 'analytics', 'analytics': 'analytics', 'pattern': 'pattern', 'patterns': 'pattern', 'recognition': 'recognition', 'mathematical': 'mathematics', 'mathematics': 'mathematics', 'research': 'research', 'researcher': 'research', 'skills': 'skills', 'ux': 'ux', 'designer': 'design', 'design': 'design', 'user': 'user', 'users': 'user', 'friendly': 'friendly', 'interfaces': 'interfaces', 'interface': 'interfaces', 'improve': 'improve', 'improvement': 'improve', 'experience': 'experience', 'experiences': 'experience', 'creative': 'creativity', 'creativity': 'creativity', 'empathy': 'empathy', 'visual': 'visual', 'visualizations': 'visual', 'centered': 'centered', 'network': 'network', 'networks': 'network', 'networking': 'network', 'administrator': 'administrator', 'administration': 'administrator', 'troubleshoot': 'troubleshooting', 'troubleshooting': 'troubleshooting', 'computer': 'computer', 'systems': 'systems', 'system': 'systems', 'technical': 'technical', 'patience': 'patience', 'devops': 'devops', 'implement': 'implement', 'implementations': 'implement', 'implementation': 'implement', 'ci': 'ci', 'cd': 'cd', 'pipelines': 'pipelines', 'manage': 'management', 'manager': 'management', 'management': 'management', 'cloud': 'cloud', 'infrastructure': 'infrastructure', 'automation': 'automation', 'automated': 'automation', 'mindset': 'mindset', 'continuous': 'continuous', 'learning': 'learning', 'quality': 'quality', 'assurance': 'assurance', 'tester': 'tester', 'test': 'testing', 'testing': 'testing', 'identify': 'identify', 'identifying': 'identify', 'bugs': 'bug', 'bug': 'bug', 'ensure': 'ensure', 'systematic': 'systematic', 'websites': 'websites', 'various': 'various', 'programming': 'programming', 'programs': 'programming', 'program': 'programming', 'languages': 'languages', 'language': 'languages', 'adaptability': 'adapt', 'adapt': 'adapt', 'database': 'database', 'integrity': 'integrity', 'integration': 'integrity', 'security': 'security', 'secure': 'security', 'awareness': 'awareness', 'cybersecurity': 'cybersecurity', 'analyst': 'analyst', 'monitor': 'monitor', 'monitoring': 'monitor', 'protect': 'protect', 'protection': 'protect', 'threats': 'threats', 'ethical': 'ethical', 'ethics': 'ethical', 'mobile': 'mobile', 'app': 'app', 'apps': 'app', 'ios': 'ios', 'android': 'android', 'platforms': 'platforms', 'innovation': 'innovation', 'product': 'product', 'products': 'product', 'productive': 'product', 'production': 'product', 'define': 'define', 'strategy': 'strategy', 'strategies': 'strategy', 'coordinate': 'coordinator', 'coordinator': 'coordinator', 'coordination': 'coordinator', 'strategic': 'strategic', 'leadership': 'leadership', 'communication': 'communication', 'community': 'communication', 'communities': 'communication', 'market': 'market', 'marketing': 'market', 'markets': 'market', 'decision': 'decisions', 'decisions': 'decisions', 'making': 'making', 'blockchain': 'blockchain', 'create': 'create', 'decentralized': 'decentralized', 'cryptocurrency': 'cryptocurrency', 'cryptography': 'cryptography', 'distributed': 'distributed', 'protocols': 'protocols', 'hacker': 'hacker', 'vulnerabilities': 'vulnerabilities', 'cryptographer': 'cryptographer', 'encryption': 'encryption', 'holographic': 'holographic', 'three': 'three', 'dimensional': 'dimensional', 'displays': 'displays', '3d': '3d', 'optical': 'optical', 'physics': 'physics', 'physical': 'physics', 'vision': 'vision', 'virtual': 'virtual', 'reality': 'reality', 'immersive': 'immersive', 'digital': 'digital', 'spatial': 'spatial', 'artificial': 'artificial', 'intelligence': 'intelligence', 'trainer': 'trainer', 'train': 'training', 'training': 'training', 'machine': 'machine', 'science': 'science', 'algorithm': 'algorithm', 'algorithms': 'algorithm', 'intuitive': 'intuitive', 'principles': 'principles', 'psychology': 'psychology', 'prototyping': 'prototyping', 'consultant': 'consultant', 'consulting': 'consultant', 'advise': 'advise', 'organizations': 'organization', 'organization': 'organization', 'organize': 'organization', 'risk': 'risk', 'assessment': 'assessment', 'assessments': 'assessment', 'planning': 'plan', 'plan': 'plan', 'wearable': 'wearable', 'technology': 'technology', 'technologies': 'technology', 'smart': 'smart', 'devices': 'devices', 'health': 'health', 'equipment': 'equipment', 'electronics': 'electronics', 'augmented': 'augmented', 'blend': 'blend', 'worlds': 'world', 'world': 'world', 'telepresence': 'telepresence', 'robot': 'robots', 'robots': 'robots', 'robotics': 'robots', 'operator': 'operations', 'operations': 'operations', 'control': 'control', 'remote': 'remote', 'mining': 'mining', 'currency': 'currency', 'hardware': 'hardware', 'energy': 'energy', 'twin': 'twin', 'replicas': 'replicas', 'analysis': 'analysis', 'quantum': 'quantum', 'specialist': 'specialist', 'ultra': 'ultra', 'mechanics': 'mechanics', 'swarm': 'swarm', 'groups': 'groups', 'autonomous': 'autonomous', 'working': 'working', 'together': 'together', 'sensor': 'sensor', 'precise': 'precise', 'measurement': 'measurement', 'instruments': 'instruments', 'ai': 'ai', 'auditor': 'auditor', 'evaluate': 'evaluate', 'bias': 'bias', 'fairness': 'fairness', 'accessibility': 'accessibility', 'accessible': 'accessibility', 'usable': 'usability', 'usability': 'usability', 'people': 'people', 'disabilities': 'disabilities', 'standards': 'standards', 'voice': 'voice', 'speech': 'speech', 'accuracy': 'accuracy', 'linguistics': 'linguistics', 'audio': 'audio', 'processing': 'processes', 'processes': 'processes', 'process': 'processes', 'privacy': 'privacy', 'individuals': 'individuals', 'online': 'online', 'legal': 'legal', 'knowledge': 'knowledge', 'asset': 'asset', 'recovery': 'recovery', 'help': 'help', 'retrieve': 'retrieve', 'lost': 'lost', 'files': 'files', 'content': 'content', 'moderator': 'moderator', 'moderation': 'moderator', 'review': 'review', 'reviews': 'review', 'filter': 'filter', 'appropriateness': 'appropriateness', 'cultural': 'cultural', 'safe': 'safe', 'discussion': 'discussion', 'spaces': 'spaces', 'conflict': 'conflict', 'resolution': 'resolution', 'events': 'events', 'director': 'director', 'conferences': 'conferences', 'gatherings': 'gatherings', 'project': 'project', 'projects': 'project', 'builder': 'builder', 'grow': 'grow', 'shared': 'shared', 'interests': 'interests', 'goals': 'goals', 'social': 'social', 'media': 'media', 'relationship': 'relationship', 'oversee': 'oversee', 'launch': 'launch', 'launches': 'launch', 'inclusive': 'inclusive', 'solutions': 'solutions', 'solution': 'solutions', 'customer': 'customer', 'customization': 'customer', 'customers': 'customer', 'study': 'study', 'studies': 'study', 'interactions': 'interaction', 'interaction': 'interaction', 'interact': 'interaction', 'satisfaction': 'satisfaction', 'ml': 'ml', 'python': 'python', 'tensorflow': 'tensorflow', 'statistics': 'statistics', 'architect': 'architect', 'comprehensive': 'comprehensive', 'enterprise': 'enterprise', 'compliance': 'compliance', 'owner': 'owner', 'roadmap': 'roadmap', 'agile': 'agile', 'agility': 'agile', 'methodologies': 'methodologies', 'stakeholder': 'stakeholder', 'scalable': 'scalable', 'scalability': 'scalable', 'migration': 'migration', 'aws': 'aws', 'azure': 'azure', 'microservices': 'microservices', 'cost': 'cost', 'optimization': 'optimize', 'optimize': 'optimize', 'contracts': 'contracts', 'solidity': 'solidity', 'web3': 'web3', 'javascript': 'javascript', 'senior': 'senior', 'scale': 'scale', 'architecture': 'architecture', 'multiple': 'multiple', 'lead': 'lead', 'big': 'big', 'tools': 'tools', 'tool': 'tools', 'conduct': 'conduct', 'inform': 'inform', 'methods': 'methods', 'provide': 'provide', 'expertise': 'expertise', 'support': 'support', 'sales': 'sales', 'success': 'success', 'writer': 'writer', 'documentation': 'documentation', 'writing': 'writing', 'write': 'writing', 'understanding': 'understanding', 'scrum': 'scrum', 'master': 'master', 'facilitate': 'facilitate', 'facilitation': 'facilitate', 'validation': 'validator', 'validator': 'validator', 'tracking': 'track', 'track': 'track', 'scripting': 'scripting', 'sql': 'sql', 'backup': 'backup', 'performance': 'performance', 'tuning': 'tuning', 'engaging': 'engagement', 'engagement': 'engagement', 'desk': 'desk', 'technician': 'technician', 'first': 'first', 'level': 'level', 'end': 'end', 'service': 'service', 'principal': 'principal', 'initiatives': 'initiatives', 'advanced': 'advanced', 'kubernetes': 'kubernetes', 'code': 'coding', 'coding': 'coding', 'wide': 'wide', 'complex': 'complex', 'mentoring': 'mentoring', 'head': 'head', 'portfolio': 'portfolio', 'direction': 'direction', 'vp': 'vp', 'site': 'site', 'reliability': 'reliability', 'incident': 'incident', 'response': 'response', 'responsible': 'response', 'junior': 'junior', 'guidance': 'guidance', 'debugging': 'debugging', 'version': 'version', 'issues': 'issues', 'installation': 'installer', 'installer': 'installer', 'client': 'clients', 'clients': 'clients', 'cisco': 'cisco', 'excellence': 'excellence', 'delivery': 'delivery', 'workflows': 'workflows', 'cross': 'cross', 'functional': 'functions', 'functions': 'functions', 'prompt': 'prompt', 'prompts': 'prompt', 'nlp': 'nlp', 'experimentation': 'experimentation', 'conversational': 'conversational', 'conversation': 'conversational', 'activated': 'activated', 'policy': 'policy', 'policies': 'policy', 'home': 'home', 'set': 'set', 'configure': 'configure', 'real': 'real', 'simulation': 'simulation', 'iot': 'iot', 'reporting': 'reporting', 'report': 'reporting', 'personal': 'personal', 'personalize': 'personal', 'coach': 'coach', 'coaching': 'coach', 'lives': 'lives', 'verify': 'verify', 'labeling': 'labeling', 'supervisor': 'supervisor', 'tagging': 'tagging', 'annotation': 'annotation', 'safety': 'safety', 'vr': 'vr', 'based': 'base', 'base': 'base', 'instructional': 'instructional', 'interviewer': 'interview', 'interviews': 'interview', 'interviewing': 'interview', 'interview': 'interview', 'objectivity': 'objectivity', 'resources': 'resources', 'chatbot': 'chatbot', 'flows': 'flows', 'assistants': 'assistants', 'new': 'new', 'account': 'account', 'afar': 'afar', 'boost': 'boost', 'participation': 'participation', 'feedback': 'feedback', 'collect': 'collect', 'manuals': 'manuals', 'rollouts': 'rollouts', 'officer': 'officer', 'advocate': 'advocate', 'promote': 'promote', 'tech': 'tech', 'advocacy': 'advocacy', 'ease': 'ease', 'journey': 'journey', 'map': 'map', 'guidelines': 'guidelines', 'driven': 'driven', 'assessor': 'assessor', 'candidates': 'candidates', 'job': 'job', 'lifecycle': 'lifecycle', 'stages': 'stages', 'growth': 'growth', 'membership': 'membership', 'hacking': 'hacking', 'localization': 'localization', 'global': 'global', 'translation': 'translation', 'champion': 'champion', 'needs': 'needs', 'crisis': 'crisis', 'handle': 'handle', 'emergencies': 'emergencies', 'input': 'input', 'guides': 'guide', 'guide': 'guide', 'find': 'find', 'scheduler': 'scheduler', 'scheduling': 'scheduler', 'timelines': 'timelines', 'beta': 'beta', 'try': 'try', 'features': 'feature', 'feature': 'feature', 'milestones': 'milestones', 'check': 'check', 'release': 'release', 'releases': 'release', 'articles': 'articles', 'behavior': 'behavior', 'employee': 'employee', 'prioritization': 'prioritization', 'rank': 'rank', 'ideas': 'ideas', 'usage': 'usage', 'interpretation': 'interpretation', 'abuse': 'abuse', 'questions': 'questions', 'creation': 'creation', 'suggestions': 'suggestions', 'meet': 'meet', 'auditing': 'audit', 'audit': 'audit', 'teach': 'teach', 'best': 'best', 'practices': 'practices', 'dashboard': 'dashboard', 'persona': 'persona', 'profiles': 'profiles', 'posts': 'posts', 'describe': 'describe', 'saas': 'saas', 'marketplace': 'marketplace', 'fraud': 'fraud', 'detect': 'detect', 'detection': 'detect', 'prevent': 'prevent', 'commerce': 'commerce', 'investigation': 'investigation', 'enforce': 'enforce', 'onboarding': 'onboarding', 'setup': 'setup', 'qa': 'qa', 'deliver': 'deliver', 'curriculum': 'curriculum', 'drive': 'drive', 'increase': 'increase', 'loyalty': 'loyalty', 'enhance': 'enhance', 'campaign': 'campaign', 'campaigns': 'campaign', 'partnership': 'partnerships', 'partnerships': 'partnerships', 'negotiation': 'negotiation', 'retention': 'retention'}

In [29]:
def normalize_vocabulary(freq_dict, family_mapping):
    normalized_freq = Counter()

    for word, count in freq_dict.items():
        canonical = family_mapping.get(word, word)
        normalized_freq[canonical] += count

    return normalized_freq

In [30]:
normalized_vocab_by_industry = {}
for industry, freq_dict in vocab_by_industry.items():
    family_mapping = canonical_mapping_by_industry[industry]
    normalized_freq = normalize_vocabulary(freq_dict, family_mapping)
    normalized_vocab_by_industry[industry] = normalized_freq
print(normalized_vocab_by_industry["technology"])

Counter({'product': 170, 'communication': 161, 'digital': 160, 'technology': 117, 'management': 78, 'remote': 67, 'analytics': 61, 'lead': 58, 'online': 53, 'technical': 51, 'design': 50, 'user': 50, 'reporting': 49, 'development': 44, 'problem': 42, 'solving': 42, 'analyst': 38, 'systems': 36, 'leadership': 36, 'data': 35, 'experience': 32, 'strategy': 30, 'support': 28, 'engineering': 27, 'customer': 26, 'teams': 25, 'security': 24, 'organization': 24, 'ux': 23, 'content': 23, 'documentation': 23, 'testing': 22, 'programming': 21, 'tools': 21, 'software': 20, 'innovation': 20, 'training': 18, 'analysis': 18, 'research': 17, 'growth': 17, 'skills': 16, 'create': 16, 'learning': 15, 'applications': 14, 'attention': 14, 'detail': 14, 'thinking': 14, 'analyze': 14, 'accessibility': 14, 'project': 14, 'writing': 14, 'ai': 13, 'cybersecurity': 12, 'help': 12, 'engagement': 12, 'campaign': 12, 'partnerships': 12, 'build': 11, 'creativity': 11, 'troubleshooting': 11, 'oversee': 11, 'service': 11, 'quality': 10, 'coordinator': 10, 'assessment': 10, 'feedback': 10, 'maintain': 9, 'insights': 9, 'models': 9, 'improve': 9, 'network': 9, 'automation': 9, 'machine': 9, 'groups': 9, 'safety': 9, 'reasoning': 8, 'market': 8, 'virtual': 8, 'specialist': 8, 'optimize': 8, 'infrastructure': 7, 'tester': 7, 'monitor': 7, 'ethical': 7, 'distributed': 7, 'protocols': 7, 'usability': 7, 'solutions': 7, 'architecture': 7, 'provide': 7, 'use': 6, 'critical': 6, 'interfaces': 6, 'cloud': 6, 'ensure': 6, 'science': 6, 'risk': 6, 'operations': 6, 'review': 6, 'launch': 6, 'compliance': 6, 'loyalty': 6, 'retention': 6, 'logical': 5, 'administrator': 5, 'implement': 5, 'assurance': 5, 'database': 5, 'awareness': 5, 'app': 5, 'platforms': 5, 'strategic': 5, 'decisions': 5, 'physics': 5, 'prototyping': 5, 'consultant': 5, 'robots': 5, 'quantum': 5, 'standards': 5, 'privacy': 5, 'knowledge': 5, 'moderator': 5, 'interaction': 5, 'architect': 5, 'enterprise': 5, 'agile': 5, 'principal': 5, 'advanced': 5, 'coding': 5, 'policy': 5, 'new': 5, 'release': 5, 'web': 4, 'business': 4, 'visual': 4, 'computer': 4, 'devops': 4, 'integrity': 4, 'protect': 4, 'cryptography': 4, 'trainer': 4, 'voice': 4, 'processes': 4, 'study': 4, 'writer': 4, 'track': 4, 'performance': 4, 'interview': 4, 'advocacy': 4, 'scheduler': 4, 'interpretation': 4, 'increase': 4, 'negotiation': 4, 'collaboration': 3, 'recognition': 3, 'empathy': 3, 'pipelines': 3, 'continuous': 3, 'websites': 3, 'languages': 3, 'define': 3, 'blockchain': 3, 'cryptocurrency': 3, '3d': 3, 'reality': 3, 'advise': 3, 'plan': 3, 'smart': 3, 'control': 3, 'hardware': 3, 'asset': 3, 'spaces': 3, 'inclusive': 3, 'python': 3, 'roadmap': 3, 'methodologies': 3, 'stakeholder': 3, 'senior': 3, 'scripting': 3, 'desk': 3, 'initiatives': 3, 'portfolio': 3, 'reliability': 3, 'response': 3, 'clients': 3, 'prompt': 3, 'conversational': 3, 'home': 3, 'chatbot': 3, 'localization': 3, 'translation': 3, 'crisis': 3, 'feature': 3, 'saas': 3, 'fraud': 3, 'drive': 3, 'frameworks': 2, 'scientist': 2, 'large': 2, 'pattern': 2, 'mathematics': 2, 'centered': 2, 'patience': 2, 'ci': 2, 'cd': 2, 'identify': 2, 'bug': 2, 'various': 2, 'adapt': 2, 'mobile': 2, 'making': 2, 'decentralized': 2, 'hacker': 2, 'vulnerabilities': 2, 'vision': 2, 'spatial': 2, 'artificial': 2, 'intelligence': 2, 'algorithm': 2, 'intuitive': 2, 'psychology': 2, 'devices': 2, 'world': 2, 'mining': 2, 'twin': 2, 'ultra': 2, 'auditor': 2, 'evaluate': 2, 'people': 2, 'disabilities': 2, 'accuracy': 2, 'individuals': 2, 'recovery': 2, 'conflict': 2, 'resolution': 2, 'director': 2, 'social': 2, 'media': 2, 'statistics': 2, 'scalable': 2, 'conduct': 2, 'sales': 2, 'facilitate': 2, 'validator': 2, 'sql': 2, 'level': 2, 'complex': 2, 'mentoring': 2, 'head': 2, 'vp': 2, 'installer': 2, 'excellence': 2, 'functions': 2, 'set': 2, 'personal': 2, 'coach': 2, 'supervisor': 2, 'vr': 2, 'base': 2, 'instructional': 2, 'objectivity': 2, 'resources': 2, 'account': 2, 'boost': 2, 'participation': 2, 'manuals': 2, 'advocate': 2, 'promote': 2, 'tech': 2, 'guide': 2, 'beta': 2, 'usage': 2, 'audit': 2, 'dashboard': 2, 'persona': 2, 'detect': 2, 'commerce': 2, 'onboarding': 2, 'qa': 2, 'curriculum': 2, 'enhance': 2, 'modern': 1, 'datasets': 1, 'extract': 1, 'predictive': 1, 'friendly': 1, 'mindset': 1, 'systematic': 1, 'threats': 1, 'ios': 1, 'android': 1, 'cryptographer': 1, 'encryption': 1, 'holographic': 1, 'three': 1, 'dimensional': 1, 'displays': 1, 'optical': 1, 'immersive': 1, 'principles': 1, 'wearable': 1, 'health': 1, 'equipment': 1, 'electronics': 1, 'augmented': 1, 'blend': 1, 'telepresence': 1, 'currency': 1, 'energy': 1, 'replicas': 1, 'mechanics': 1, 'swarm': 1, 'autonomous': 1, 'working': 1, 'together': 1, 'sensor': 1, 'precise': 1, 'measurement': 1, 'instruments': 1, 'bias': 1, 'fairness': 1, 'speech': 1, 'linguistics': 1, 'audio': 1, 'legal': 1, 'retrieve': 1, 'lost': 1, 'files': 1, 'filter': 1, 'appropriateness': 1, 'cultural': 1, 'safe': 1, 'discussion': 1, 'events': 1, 'conferences': 1, 'gatherings': 1, 'builder': 1, 'grow': 1, 'shared': 1, 'interests': 1, 'goals': 1, 'relationship': 1, 'satisfaction': 1, 'ml': 1, 'tensorflow': 1, 'comprehensive': 1, 'owner': 1, 'migration': 1, 'aws': 1, 'azure': 1, 'microservices': 1, 'cost': 1, 'contracts': 1, 'solidity': 1, 'web3': 1, 'javascript': 1, 'scale': 1, 'multiple': 1, 'big': 1, 'inform': 1, 'methods': 1, 'expertise': 1, 'success': 1, 'understanding': 1, 'scrum': 1, 'master': 1, 'backup': 1, 'tuning': 1, 'technician': 1, 'first': 1, 'end': 1, 'kubernetes': 1, 'wide': 1, 'direction': 1, 'site': 1, 'incident': 1, 'junior': 1, 'guidance': 1, 'debugging': 1, 'version': 1, 'issues': 1, 'cisco': 1, 'delivery': 1, 'workflows': 1, 'cross': 1, 'nlp': 1, 'experimentation': 1, 'activated': 1, 'configure': 1, 'real': 1, 'simulation': 1, 'iot': 1, 'lives': 1, 'verify': 1, 'labeling': 1, 'tagging': 1, 'annotation': 1, 'flows': 1, 'assistants': 1, 'afar': 1, 'collect': 1, 'rollouts': 1, 'officer': 1, 'ease': 1, 'journey': 1, 'map': 1, 'guidelines': 1, 'driven': 1, 'assessor': 1, 'candidates': 1, 'job': 1, 'lifecycle': 1, 'stages': 1, 'membership': 1, 'hacking': 1, 'global': 1, 'champion': 1, 'needs': 1, 'handle': 1, 'emergencies': 1, 'input': 1, 'find': 1, 'timelines': 1, 'try': 1, 'milestones': 1, 'check': 1, 'articles': 1, 'behavior': 1, 'employee': 1, 'prioritization': 1, 'rank': 1, 'ideas': 1, 'abuse': 1, 'questions': 1, 'creation': 1, 'suggestions': 1, 'meet': 1, 'teach': 1, 'best': 1, 'practices': 1, 'profiles': 1, 'posts': 1, 'describe': 1, 'marketplace': 1, 'prevent': 1, 'investigation': 1, 'enforce': 1, 'setup': 1, 'deliver': 1})

In [31]:
def normalize_vocabulary_by_industry(vocab_by_industry):
    normalized_vocab_by_industry = {}
    mapping_by_industry = {}
    canonical_info_by_industry = {}

    for industry, freq_dict in vocab_by_industry.items():
        stem_groups = group_family_words(freq_dict)
        family_mapping, canonical_info = choose_canonical_word(stem_groups)
        normalized_freq = normalize_vocabulary(freq_dict, family_mapping)

        normalized_vocab_by_industry[industry] = normalized_freq
        mapping_by_industry[industry] = family_mapping
        canonical_info_by_industry[industry] = canonical_info

    return normalized_vocab_by_industry, mapping_by_industry, canonical_info_by_industry
# output sẽ có dạng:
# normalized_vocab_by_industry = {
#     "Software": Counter({"develop": 240, "test": 150, ...}),
#     "Finance": Counter({"analyz": 180, "report": 120, ...}),
#     ...
# },
# mapping_by_industry = {
#     "Software": {"develop": "develop", "developer": "develop", "development": "develop", ...},
#     "Finance": {"analyz": "analyz", "analyze":
#         "analyz", "report": "report", ...},
#     ...
# },
# canonical_info_by_industry = {
#     "Software": {
#         "develop": {
#             "canonical": "develop",
#             "variants": [("develop", 100), ("developer", 80), ("development", 60)]
#         },
#         ...
#     },
#     ...
# }

In [33]:
normalized_vocab_by_industry = {}
for industry, freq_dict in vocab_by_industry.items():
    family_mapping = canonical_mapping_by_industry[industry]
    normalized_freq = normalize_vocabulary(freq_dict, family_mapping)
    normalized_vocab_by_industry[industry] = normalized_freq
print(normalized_vocab_by_industry["technology"])

Counter({'product': 170, 'communication': 161, 'digital': 160, 'technology': 117, 'management': 78, 'remote': 67, 'analytics': 61, 'lead': 58, 'online': 53, 'technical': 51, 'design': 50, 'user': 50, 'reporting': 49, 'development': 44, 'problem': 42, 'solving': 42, 'analyst': 38, 'systems': 36, 'leadership': 36, 'data': 35, 'experience': 32, 'strategy': 30, 'support': 28, 'engineering': 27, 'customer': 26, 'teams': 25, 'security': 24, 'organization': 24, 'ux': 23, 'content': 23, 'documentation': 23, 'testing': 22, 'programming': 21, 'tools': 21, 'software': 20, 'innovation': 20, 'training': 18, 'analysis': 18, 'research': 17, 'growth': 17, 'skills': 16, 'create': 16, 'learning': 15, 'applications': 14, 'attention': 14, 'detail': 14, 'thinking': 14, 'analyze': 14, 'accessibility': 14, 'project': 14, 'writing': 14, 'ai': 13, 'cybersecurity': 12, 'help': 12, 'engagement': 12, 'campaign': 12, 'partnerships': 12, 'build': 11, 'creativity': 11, 'troubleshooting': 11, 'oversee': 11, 'service': 11, 'quality': 10, 'coordinator': 10, 'assessment': 10, 'feedback': 10, 'maintain': 9, 'insights': 9, 'models': 9, 'improve': 9, 'network': 9, 'automation': 9, 'machine': 9, 'groups': 9, 'safety': 9, 'reasoning': 8, 'market': 8, 'virtual': 8, 'specialist': 8, 'optimize': 8, 'infrastructure': 7, 'tester': 7, 'monitor': 7, 'ethical': 7, 'distributed': 7, 'protocols': 7, 'usability': 7, 'solutions': 7, 'architecture': 7, 'provide': 7, 'use': 6, 'critical': 6, 'interfaces': 6, 'cloud': 6, 'ensure': 6, 'science': 6, 'risk': 6, 'operations': 6, 'review': 6, 'launch': 6, 'compliance': 6, 'loyalty': 6, 'retention': 6, 'logical': 5, 'administrator': 5, 'implement': 5, 'assurance': 5, 'database': 5, 'awareness': 5, 'app': 5, 'platforms': 5, 'strategic': 5, 'decisions': 5, 'physics': 5, 'prototyping': 5, 'consultant': 5, 'robots': 5, 'quantum': 5, 'standards': 5, 'privacy': 5, 'knowledge': 5, 'moderator': 5, 'interaction': 5, 'architect': 5, 'enterprise': 5, 'agile': 5, 'principal': 5, 'advanced': 5, 'coding': 5, 'policy': 5, 'new': 5, 'release': 5, 'web': 4, 'business': 4, 'visual': 4, 'computer': 4, 'devops': 4, 'integrity': 4, 'protect': 4, 'cryptography': 4, 'trainer': 4, 'voice': 4, 'processes': 4, 'study': 4, 'writer': 4, 'track': 4, 'performance': 4, 'interview': 4, 'advocacy': 4, 'scheduler': 4, 'interpretation': 4, 'increase': 4, 'negotiation': 4, 'collaboration': 3, 'recognition': 3, 'empathy': 3, 'pipelines': 3, 'continuous': 3, 'websites': 3, 'languages': 3, 'define': 3, 'blockchain': 3, 'cryptocurrency': 3, '3d': 3, 'reality': 3, 'advise': 3, 'plan': 3, 'smart': 3, 'control': 3, 'hardware': 3, 'asset': 3, 'spaces': 3, 'inclusive': 3, 'python': 3, 'roadmap': 3, 'methodologies': 3, 'stakeholder': 3, 'senior': 3, 'scripting': 3, 'desk': 3, 'initiatives': 3, 'portfolio': 3, 'reliability': 3, 'response': 3, 'clients': 3, 'prompt': 3, 'conversational': 3, 'home': 3, 'chatbot': 3, 'localization': 3, 'translation': 3, 'crisis': 3, 'feature': 3, 'saas': 3, 'fraud': 3, 'drive': 3, 'frameworks': 2, 'scientist': 2, 'large': 2, 'pattern': 2, 'mathematics': 2, 'centered': 2, 'patience': 2, 'ci': 2, 'cd': 2, 'identify': 2, 'bug': 2, 'various': 2, 'adapt': 2, 'mobile': 2, 'making': 2, 'decentralized': 2, 'hacker': 2, 'vulnerabilities': 2, 'vision': 2, 'spatial': 2, 'artificial': 2, 'intelligence': 2, 'algorithm': 2, 'intuitive': 2, 'psychology': 2, 'devices': 2, 'world': 2, 'mining': 2, 'twin': 2, 'ultra': 2, 'auditor': 2, 'evaluate': 2, 'people': 2, 'disabilities': 2, 'accuracy': 2, 'individuals': 2, 'recovery': 2, 'conflict': 2, 'resolution': 2, 'director': 2, 'social': 2, 'media': 2, 'statistics': 2, 'scalable': 2, 'conduct': 2, 'sales': 2, 'facilitate': 2, 'validator': 2, 'sql': 2, 'level': 2, 'complex': 2, 'mentoring': 2, 'head': 2, 'vp': 2, 'installer': 2, 'excellence': 2, 'functions': 2, 'set': 2, 'personal': 2, 'coach': 2, 'supervisor': 2, 'vr': 2, 'base': 2, 'instructional': 2, 'objectivity': 2, 'resources': 2, 'account': 2, 'boost': 2, 'participation': 2, 'manuals': 2, 'advocate': 2, 'promote': 2, 'tech': 2, 'guide': 2, 'beta': 2, 'usage': 2, 'audit': 2, 'dashboard': 2, 'persona': 2, 'detect': 2, 'commerce': 2, 'onboarding': 2, 'qa': 2, 'curriculum': 2, 'enhance': 2, 'modern': 1, 'datasets': 1, 'extract': 1, 'predictive': 1, 'friendly': 1, 'mindset': 1, 'systematic': 1, 'threats': 1, 'ios': 1, 'android': 1, 'cryptographer': 1, 'encryption': 1, 'holographic': 1, 'three': 1, 'dimensional': 1, 'displays': 1, 'optical': 1, 'immersive': 1, 'principles': 1, 'wearable': 1, 'health': 1, 'equipment': 1, 'electronics': 1, 'augmented': 1, 'blend': 1, 'telepresence': 1, 'currency': 1, 'energy': 1, 'replicas': 1, 'mechanics': 1, 'swarm': 1, 'autonomous': 1, 'working': 1, 'together': 1, 'sensor': 1, 'precise': 1, 'measurement': 1, 'instruments': 1, 'bias': 1, 'fairness': 1, 'speech': 1, 'linguistics': 1, 'audio': 1, 'legal': 1, 'retrieve': 1, 'lost': 1, 'files': 1, 'filter': 1, 'appropriateness': 1, 'cultural': 1, 'safe': 1, 'discussion': 1, 'events': 1, 'conferences': 1, 'gatherings': 1, 'builder': 1, 'grow': 1, 'shared': 1, 'interests': 1, 'goals': 1, 'relationship': 1, 'satisfaction': 1, 'ml': 1, 'tensorflow': 1, 'comprehensive': 1, 'owner': 1, 'migration': 1, 'aws': 1, 'azure': 1, 'microservices': 1, 'cost': 1, 'contracts': 1, 'solidity': 1, 'web3': 1, 'javascript': 1, 'scale': 1, 'multiple': 1, 'big': 1, 'inform': 1, 'methods': 1, 'expertise': 1, 'success': 1, 'understanding': 1, 'scrum': 1, 'master': 1, 'backup': 1, 'tuning': 1, 'technician': 1, 'first': 1, 'end': 1, 'kubernetes': 1, 'wide': 1, 'direction': 1, 'site': 1, 'incident': 1, 'junior': 1, 'guidance': 1, 'debugging': 1, 'version': 1, 'issues': 1, 'cisco': 1, 'delivery': 1, 'workflows': 1, 'cross': 1, 'nlp': 1, 'experimentation': 1, 'activated': 1, 'configure': 1, 'real': 1, 'simulation': 1, 'iot': 1, 'lives': 1, 'verify': 1, 'labeling': 1, 'tagging': 1, 'annotation': 1, 'flows': 1, 'assistants': 1, 'afar': 1, 'collect': 1, 'rollouts': 1, 'officer': 1, 'ease': 1, 'journey': 1, 'map': 1, 'guidelines': 1, 'driven': 1, 'assessor': 1, 'candidates': 1, 'job': 1, 'lifecycle': 1, 'stages': 1, 'membership': 1, 'hacking': 1, 'global': 1, 'champion': 1, 'needs': 1, 'handle': 1, 'emergencies': 1, 'input': 1, 'find': 1, 'timelines': 1, 'try': 1, 'milestones': 1, 'check': 1, 'articles': 1, 'behavior': 1, 'employee': 1, 'prioritization': 1, 'rank': 1, 'ideas': 1, 'abuse': 1, 'questions': 1, 'creation': 1, 'suggestions': 1, 'meet': 1, 'teach': 1, 'best': 1, 'practices': 1, 'profiles': 1, 'posts': 1, 'describe': 1, 'marketplace': 1, 'prevent': 1, 'investigation': 1, 'enforce': 1, 'setup': 1, 'deliver': 1})

In [35]:
def build_vocab_list_by_industry(normalized_vocab_by_industry):
    vocab_list_by_industry = {}

    for industry, freq_dict in normalized_vocab_by_industry.items():
        vocab_list_by_industry[industry] = list(freq_dict.keys())

    return vocab_list_by_industry

In [36]:
vocab_list_by_industry = build_vocab_list_by_industry(normalized_vocab_by_industry)
print(vocab_list_by_industry["technology"])

['software', 'engineering', 'development', 'maintain', 'web', 'applications', 'use', 'modern', 'frameworks', 'problem', 'solving', 'logical', 'reasoning', 'attention', 'detail', 'teams', 'collaboration', 'critical', 'thinking', 'data', 'scientist', 'analyze', 'large', 'datasets', 'extract', 'business', 'insights', 'build', 'predictive', 'models', 'analytics', 'pattern', 'recognition', 'mathematics', 'research', 'skills', 'ux', 'design', 'user', 'friendly', 'interfaces', 'improve', 'experience', 'creativity', 'empathy', 'visual', 'centered', 'network', 'administrator', 'troubleshooting', 'computer', 'systems', 'technical', 'patience', 'devops', 'implement', 'ci', 'cd', 'pipelines', 'management', 'cloud', 'infrastructure', 'automation', 'mindset', 'continuous', 'learning', 'quality', 'assurance', 'tester', 'testing', 'identify', 'bug', 'ensure', 'systematic', 'websites', 'various', 'programming', 'languages', 'adapt', 'database', 'integrity', 'security', 'awareness', 'cybersecurity', 'analyst', 'monitor', 'protect', 'threats', 'ethical', 'mobile', 'app', 'ios', 'android', 'platforms', 'innovation', 'product', 'define', 'strategy', 'coordinator', 'strategic', 'leadership', 'communication', 'market', 'decisions', 'making', 'blockchain', 'create', 'decentralized', 'cryptocurrency', 'cryptography', 'distributed', 'protocols', 'hacker', 'vulnerabilities', 'cryptographer', 'encryption', 'holographic', 'three', 'dimensional', 'displays', '3d', 'optical', 'physics', 'vision', 'virtual', 'reality', 'immersive', 'digital', 'spatial', 'artificial', 'intelligence', 'trainer', 'training', 'machine', 'science', 'algorithm', 'intuitive', 'principles', 'psychology', 'prototyping', 'consultant', 'advise', 'organization', 'risk', 'assessment', 'plan', 'wearable', 'technology', 'smart', 'devices', 'health', 'equipment', 'electronics', 'augmented', 'blend', 'world', 'telepresence', 'robots', 'operations', 'control', 'remote', 'mining', 'currency', 'hardware', 'energy', 'twin', 'replicas', 'analysis', 'quantum', 'specialist', 'ultra', 'mechanics', 'swarm', 'groups', 'autonomous', 'working', 'together', 'sensor', 'precise', 'measurement', 'instruments', 'ai', 'auditor', 'evaluate', 'bias', 'fairness', 'accessibility', 'usability', 'people', 'disabilities', 'standards', 'voice', 'speech', 'accuracy', 'linguistics', 'audio', 'processes', 'privacy', 'individuals', 'online', 'legal', 'knowledge', 'asset', 'recovery', 'help', 'retrieve', 'lost', 'files', 'content', 'moderator', 'review', 'filter', 'appropriateness', 'cultural', 'safe', 'discussion', 'spaces', 'conflict', 'resolution', 'events', 'director', 'conferences', 'gatherings', 'project', 'builder', 'grow', 'shared', 'interests', 'goals', 'social', 'media', 'relationship', 'oversee', 'launch', 'inclusive', 'solutions', 'customer', 'study', 'interaction', 'satisfaction', 'ml', 'python', 'tensorflow', 'statistics', 'architect', 'comprehensive', 'enterprise', 'compliance', 'owner', 'roadmap', 'agile', 'methodologies', 'stakeholder', 'scalable', 'migration', 'aws', 'azure', 'microservices', 'cost', 'optimize', 'contracts', 'solidity', 'web3', 'javascript', 'senior', 'scale', 'architecture', 'multiple', 'lead', 'big', 'tools', 'conduct', 'inform', 'methods', 'provide', 'expertise', 'support', 'sales', 'success', 'writer', 'documentation', 'writing', 'understanding', 'scrum', 'master', 'facilitate', 'validator', 'track', 'scripting', 'sql', 'backup', 'performance', 'tuning', 'engagement', 'desk', 'technician', 'first', 'level', 'end', 'service', 'principal', 'initiatives', 'advanced', 'kubernetes', 'coding', 'wide', 'complex', 'mentoring', 'head', 'portfolio', 'direction', 'vp', 'site', 'reliability', 'incident', 'response', 'junior', 'guidance', 'debugging', 'version', 'issues', 'installer', 'clients', 'cisco', 'excellence', 'delivery', 'workflows', 'cross', 'functions', 'prompt', 'nlp', 'experimentation', 'conversational', 'activated', 'policy', 'home', 'set', 'configure', 'real', 'simulation', 'iot', 'reporting', 'personal', 'coach', 'lives', 'verify', 'labeling', 'supervisor', 'tagging', 'annotation', 'safety', 'vr', 'base', 'instructional', 'interview', 'objectivity', 'resources', 'chatbot', 'flows', 'assistants', 'new', 'account', 'afar', 'boost', 'participation', 'feedback', 'collect', 'manuals', 'rollouts', 'officer', 'advocate', 'promote', 'tech', 'advocacy', 'ease', 'journey', 'map', 'guidelines', 'driven', 'assessor', 'candidates', 'job', 'lifecycle', 'stages', 'growth', 'membership', 'hacking', 'localization', 'global', 'translation', 'champion', 'needs', 'crisis', 'handle', 'emergencies', 'input', 'guide', 'find', 'scheduler', 'timelines', 'beta', 'try', 'feature', 'milestones', 'check', 'release', 'articles', 'behavior', 'employee', 'prioritization', 'rank', 'ideas', 'usage', 'interpretation', 'abuse', 'questions', 'creation', 'suggestions', 'meet', 'audit', 'teach', 'best', 'practices', 'dashboard', 'persona', 'profiles', 'posts', 'describe', 'saas', 'marketplace', 'fraud', 'detect', 'prevent', 'commerce', 'investigation', 'enforce', 'onboarding', 'setup', 'qa', 'deliver', 'curriculum', 'drive', 'increase', 'loyalty', 'enhance', 'campaign', 'partnerships', 'negotiation', 'retention']

In [37]:
def export_vocab_comma_format(normalized_vocab_by_industry, output_path="industry_vocab.csv"):
    rows = []

    for industry, freq_dict in normalized_vocab_by_industry.items():
        vocab_list = list(freq_dict.keys())

        rows.append({
            "Industry": industry,
            "vocab": ", ".join(vocab_list)
        })

    df = pd.DataFrame(rows)
    df.to_csv(output_path, index=False, encoding="utf-8-sig")
    return df

In [38]:
export_df = export_vocab_comma_format(normalized_vocab_by_industry)
export_df.head()

          Industry                                              vocab
0      advertising  advertising, executive, develop, implement, ca...
1        aerospace  space, mission, planner, design, coordinate, e...
2      agriculture  farmer, grow, crop, raise, livestock, food, pr...
3  animal sciences  animal, behaviorist, study, modify, behavior, ...
4  animal services  pet, grief, counselor, support, families, loss...